export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOAD_FAILED = 'USER_LOAD_FAILED';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';


export const NOW_VAULT_LOADING = 'NOW_VAULT_LOADING';
export const NOW_VAULT_LOADED = 'NOW_VAULT_LOADED';

export const INCOME_LOADING = 'INCOME_LOADING';
export const INCOME_LOADED = 'INCOME_LOADED';

export const EXPENSE_LOADING = 'EXPENSE_LOADING';
export const EXPENSE_LOADED = 'EXPENSE_LOADED';

export const RECEIVED_LOADING = 'RECEIVED_LOADING';
export const RECEIVED_LOADED = 'RECEIVED_LOADED';